### ISSUE TITLE
not working in windows 11

### ISSUE THREAD

**Issue by hosseinkhojany** [InvisibleManVPN/InvisibleMan-TUN#6]
It can be seen here that no adapter has been created in the Windows connections section
![Screenshot 2023-05-04 213000](https://user-images.githubusercontent.com/37432839/236274519-069f2c09-dc13-4aaf-98ed-1dd97d05473b.png)

**Comment by InvisibleManVPN** [comment]
Hi @hosseinkhojany!
Thanks for this issue. You need to write your own client to communicate with this service. It cannot be used without any client. Your client should send its commands to this service from a socket.
For more information read [this](https://github.com/InvisibleManVPN/InvisibleMan-TUN#communicate-with-the-service).
Also, we used this service in our **Invisible Man - XRay** product. You can read [InvisibleMan-XRay/Handlers/Services/TunnelService.cs](https://github.com/InvisibleManVPN/InvisibleMan-XRayClient/blob/master/InvisibleMan-XRay/Handlers/Services/TunnelService.cs) file to know how we communicated the app with this service.

**Comment by hosseinkhojany** [comment]
Thanks

**Comment by mbashirim** [comment]
> Also, we used this service in our **Invisible Man - XRay** product. You can read [InvisibleMan-XRay/Handlers/Services/TunnelService.cs](https://github.com/InvisibleManVPN/InvisibleMan-XRayClient/blob/master/InvisibleMan-XRay/Handlers/Services/TunnelService.cs) file to know how we communicated the app with this service.

is it removed? cus it returns 404 error!
i just wanted to use this with xray client to tunnel all my pc network
