### ISSUE TITLE
Hello I want a new feature plz to implement tun in any language without opening new terminal windows

### ISSUE THREAD

**Issue by hosseinkhojany** [InvisibleManVPN/InvisibleMan-TUN#7]
When I run invisibleman-tun.exe -port=2223 into cmd, a new terminal is opened. Is it possible to continue working in the background without opening a new terminal? 
I already tried to do this in C++ with CreateProcess but the socket is always off 
here is my cpp code:

    ``` STARTUPINFO startupInfo;
    PROCESS_INFORMATION processInfo;
    ZeroMemory(&startupInfo, sizeof(startupInfo));
    startupInfo.cb = sizeof(startupInfo);
    startupInfo.dwFlags = STARTF_USESHOWWINDOW;
    startupInfo.wShowWindow = SW_HIDE;
    ZeroMemory(&processInfo, sizeof(processInfo));
    LPSTR cmdLine = const_cast<LPSTR>("-port=2223");
    if (!CreateProcess("./tun.exe", cmdLine, NULL, NULL, TRUE, CREATE_NO_WINDOW, NULL, NULL, &startupInfo, &processInfo))
    {
        std::cerr << "Error creating process: " << GetLastError() << std::endl;
        return 1;
    }
    WaitForSingleObject(processInfo.hProcess, INFINITE);
    CloseHandle(processInfo.hProcess);
    CloseHandle(processInfo.hThread); ```
    
   this code done without error but socket not working

**Comment by InvisibleManVPN** [comment]
Hi @hosseinkhojany!
Invisible Man TUN needs administrator privilege to work properly. So, to run the service without opening a new terminal, you need to run your program as administrator.
Also, can you show me how you make a socket connection between your app and tun service?

**Comment by hosseinkhojany** [comment]
Honestly, my program in Flutter(dart) connects to TUN socket
await Socket.connect("127.0.0.2", 2223, sourcePort: 2223);
            String command =
                "-command=enable -device=zVPN -proxy=127.0.0.1:10801 -address=10.0.236.10 -server=${selectedVpnService
                .config?.vlessConfig != null ? selectedVpnService.config!
                .vlessConfig!.add! : selectedVpnService.config!.vmessConfig!
                .add} -dns=8.8.8.8";
            print(selectedVpnService
                .config?.vlessConfig != null ? selectedVpnService.config!
                .vlessConfig!.add! : selectedVpnService.config!.vmessConfig!
                .add!);
            String delimiter = '<EOF>';
            String message = command + delimiter;
            List<int> bytes = utf8.encode(message);
            socket?.add(bytes);

**Comment by hosseinkhojany** [comment]
Also I have customized the socket address to 127.0.0.2

**Comment by hosseinkhojany** [comment]
How to find the correct -address parameter ?
-command=enable -device=zVPN -proxy=127.0.0.1:10801 -address=`how to find this`-server=example.com -dns=8.8.8.8

**Comment by InvisibleManVPN** [comment]
@hosseinkhojany You need to find the default gateway based on the address that you set on your `wintun` adapter. There are many ways to find the network's default gateway. You can write a code to find it automatically or enter the gateway manually.
In Windows, you can find the default gateway automatically by using `iphlpapi.dll`. In **Invisible Man TUN**, I wrote a code to find the default gateway. See these files: 
- [NetworkUtility -> GetDefaultGateway(string address)](https://github.com/InvisibleManVPN/InvisibleMan-TUN/blob/2fb6b807734cb493d6d75aaae79af13be761b555/InvisibleMan-TUN/Utilities/NetworkUtility.cs#L30)
- [IPHelperWrapper.cs](https://github.com/InvisibleManVPN/InvisibleMan-TUN/blob/2fb6b807734cb493d6d75aaae79af13be761b555/InvisibleMan-TUN/Utilities/IPHelperWrapper.cs)
