### ISSUE TITLE
cannot connect to the process

### ISSUE THREAD

**Issue by AliAkhgar** [InvisibleManVPN/InvisibleMan-TUN#8]
Hi
I'm running invisibleMan-TUN with port 10802 in cmd and its running fine but the problem is that i cannot see invisibleMan listening on port 10802 with or without runasAdmin privilege.
I tested with official release from invisibleMan Xray Client and after running, i could connect to tun via telnet perfectly fine; but when i run tun in cmd, i cannot connect to it and it is not listening either.
any idea?

**Comment by InvisibleManVPN** [comment]
Hey @AliAkhgar, Thanks for submitting the issue. I already published a new release and fixed the crashing bug. Please check the new release and let me know whether the problem still exists.

Thanks!
